
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int LT = 10;
  public static final int SEMICOLON = 16;
  public static final int ELSE = 3;
  public static final int PLUS = 4;
  public static final int RBRACE = 15;
  public static final int RPAREN = 13;
  public static final int IF = 2;
  public static final int LPAREN = 12;
  public static final int GT = 9;
  public static final int LBRACE = 14;
  public static final int ID = 19;
  public static final int FLOAT = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 7;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int EQ = 8;
  public static final int INTEGER = 17;
  public static final int EQEQ = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQ",
  "GT",
  "LT",
  "EQEQ",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "INTEGER",
  "FLOAT",
  "ID"
  };
}

